In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../../data/original_data/human-development-index/human-development-index.csv")

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6570 entries, 0 to 6569
Data columns (total 5 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Entity                          6570 non-null   str
 1   Code                            5940 non-null   str
 2   Year                            6570 non-null   int64
 3   Human Development Index         6570 non-null   float64
 4   World region according to OWID  5906 non-null   str
dtypes: float64(1), int64(1), str(3)
memory usage: 256.8 KB

In [34]:
df.head(20)

,Entity,Code,Year,Human Development Index,World region according to OWID
0,Afghanistan,AFG,1990,0.285,Asia
1,Afghanistan,AFG,1991,0.291,Asia
2,Afghanistan,AFG,1992,0.301,Asia
3,Afghanistan,AFG,1993,0.311,Asia
4,Afghanistan,AFG,1994,0.305,Asia
5,Afghanistan,AFG,1995,0.329,Asia
6,Afghanistan,AFG,1996,0.334,Asia
7,Afghanistan,AFG,1997,0.338,Asia
8,Afghanistan,AFG,1998,0.338,Asia
9,Afghanistan,AFG,1999,0.347,Asia
10,Afghanistan,AFG,2000,0.351,Asia
11,Afghanistan,AFG,2001,0.355,Asia
12,Afghanistan,AFG,2002,0.383,Asia
13,Afghanistan,AFG,2003,0.392,Asia
14,Afghanistan,AFG,2004,0.408,Asia
15,Afghanistan,AFG,2005,0.417,Asia
16,Afghanistan,AFG,2006,0.426,Asia
17,Afghanistan,AFG,2007,0.442,Asia
18,Afghanistan,AFG,2008,0.446,Asia
19,Afghanistan,AFG,2009,0.458,Asia

In [5]:
len(df['Entity'].unique())

214

In [6]:
import pycountry

In [8]:
iso3_name_set = {country.alpha_3 for country in pycountry.countries}
iso3_name_set.add('XKX')

In [9]:
df_countries=df[df['Code'].isin(iso3_name_set)]

In [32]:
df_filtered = df_countries[
    (~(df['Human Development Index'].isna()))  
    & (df['Year'] == 2023)  
].reset_index(drop=True)

C:\Users\USER\AppData\Local\Temp\ipykernel_22260\2982006247.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filtered = df_countries[

## WE HAVE FILTERED DISTINCT COUNTRY VALUES FOR 2023

In [33]:
df_filtered

,Entity,Code,Year,Human Development Index,World region according to OWID
0,Afghanistan,AFG,2023,0.496,Asia
1,Albania,ALB,2023,0.810,Europe
2,Algeria,DZA,2023,0.763,Africa
3,Andorra,AND,2023,0.913,Europe
4,Angola,AGO,2023,0.616,Africa
...,...,...,...,...,...
187,Venezuela,VEN,2023,0.709,South America
188,Vietnam,VNM,2023,0.766,Asia
189,Yemen,YEM,2023,0.470,Asia
190,Zambia,ZMB,2023,0.595,Africa
191,Zimbabwe,ZWE,2023,0.598,Africa

In [17]:
average_hdi_per_entity =( df_filtered.groupby(
    'World region according to OWID',
    as_index=False)['Human Development Index']
    .mean()
    .rename(columns={'Human Development Index':'Average HDI'})
    .sort_values('Average HDI', ascending=False)
)
average_hdi_per_entity.index = range(1, len(average_hdi_per_entity) + 1)
average_hdi_per_entity

  World region according to OWID  Average HDI
1                         Europe     0.899093
2                  South America     0.787167
3                  North America     0.773435
4                           Asia     0.756630
5                        Oceania     0.718214
6                         Africa     0.579611

In [22]:
max_hdi_per_region = df_filtered.groupby('World region according to OWID')['Human Development Index'].transform('max')

df_top = df_filtered[df_filtered['Human Development Index'] == max_hdi_per_region]
df_top=df_top.sort_values('Human Development Index', ascending=False)
df_top.index = range(1, len(df_top) + 1)


df_top

,Entity,Code,Year,Human Development Index,World region according to OWID
1,Iceland,ISL,2023,0.972,Europe
2,Australia,AUS,2023,0.958,Oceania
3,Hong Kong,HKG,2023,0.955,Asia
4,Canada,CAN,2023,0.939,North America
5,Chile,CHL,2023,0.878,South America
6,Seychelles,SYC,2023,0.848,Africa

In [21]:
min_hdi_per_region = df_filtered.groupby('World region according to OWID')['Human Development Index'].transform('min')

df_bottom = df_filtered[df_filtered['Human Development Index'] == min_hdi_per_region]

df_bottom

,Entity,Code,Year,Human Development Index,World region according to OWID
2503,Haiti,HTI,2023,0.554,North America
4624,Papua New Guinea,PNG,2023,0.576,Oceania
5498,South Sudan,SSD,2023,0.388,Africa
6128,Ukraine,UKR,2023,0.779,Europe
6365,Venezuela,VEN,2023,0.709,South America
6501,Yemen,YEM,2023,0.470,Asia

In [28]:
df_africa=df_filtered[df_filtered['World region according to OWID']=='Africa'].sort_values('Human Development Index', ascending=False)
df_africa.index = range(1, len(df_africa) + 1)

In [31]:
df_africa.head(10)

,Entity,Code,Year,Human Development Index,World region according to OWID
1,Seychelles,SYC,2023,0.848,Africa
2,Mauritius,MUS,2023,0.806,Africa
3,Algeria,DZA,2023,0.763,Africa
4,Egypt,EGY,2023,0.754,Africa
5,Tunisia,TUN,2023,0.746,Africa
6,South Africa,ZAF,2023,0.741,Africa
7,Gabon,GAB,2023,0.733,Africa
8,Botswana,BWA,2023,0.731,Africa
9,Libya,LBY,2023,0.721,Africa
10,Morocco,MAR,2023,0.710,Africa