# WE WILL WORK ON REDUCING THE DATA TO ONLY THE SECTIONS WE NEED

In [1]:
import pandas as pd

### As we saw previously the data was split into regional and national info

In [2]:
import pycountry as pco

In [3]:
iso3_name_set = {country.alpha_3 for country in pco.countries}
iso3_name_set.add('XKX')

In [4]:
df = pd.read_csv('../../data/original_data/fertility-rates/fertility-rate.csv')

In [5]:
df_countries = df[df['Country Code'].isin(iso3_name_set)]
df_countries.head(10)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
0,Aruba,ABW,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,4.567,4.422,4.262,4.107,3.940,3.797,...,1.785,1.732,1.701,1.662,1.631,1.615,1.602,NaN,NaN,NaN
2,Afghanistan,AFG,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,7.282,7.284,7.292,7.302,7.304,7.305,...,5.433,5.327,5.238,5.145,5.039,4.932,4.840,NaN,NaN,NaN
4,Angola,AGO,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,6.708,6.790,6.872,6.954,7.036,7.116,...,5.600,5.519,5.442,5.371,5.304,5.209,5.124,NaN,NaN,NaN
5,Albania,ALB,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,6.383,6.273,6.106,5.927,5.714,5.474,...,1.486,1.415,1.395,1.371,1.365,1.355,1.348,NaN,NaN,NaN
6,Andorra,AND,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,2.545,2.543,2.548,2.602,2.689,2.715,...,1.129,1.053,1.045,1.028,1.058,1.071,1.082,NaN,NaN,NaN
8,United Arab Emirates,ARE,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,6.499,6.494,6.489,6.495,6.494,6.495,...,1.350,1.288,1.247,1.289,1.162,1.148,1.200,NaN,NaN,NaN
9,Argentina,ARG,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,3.136,3.120,3.126,3.109,3.075,3.005,...,2.168,2.067,1.882,1.601,1.585,1.482,1.500,NaN,NaN,NaN
10,Armenia,ARM,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,4.786,4.670,4.521,4.345,4.150,3.988,...,1.600,1.600,1.600,1.700,1.700,1.700,1.900,NaN,NaN,NaN
11,American Samoa,ASM,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,6.578,6.575,6.603,6.687,6.780,6.730,...,2.598,2.494,2.404,2.360,2.327,2.305,2.286,NaN,NaN,NaN
12,Antigua and Barbuda,ATG,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,4.602,4.559,4.547,4.536,4.484,4.416,...,1.485,1.371,1.468,1.569,1.580,1.580,1.578,NaN,NaN,NaN

In [6]:
df_groups=df[~df['Country Code'].isin(iso3_name_set)]
df_groups.head(10)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
1,Africa Eastern and Southern,AFE,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,6.650310,6.667308,6.688246,6.709226,6.724930,6.737459,...,4.569884,4.521443,4.471338,4.412973,4.350683,4.287033,4.223820,NaN,NaN,NaN
3,Africa Western and Central,AFW,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,6.468887,6.478351,6.492277,6.500229,6.516739,6.532766,...,5.098885,4.962571,4.829134,4.707399,4.637741,4.563354,4.497707,NaN,NaN,NaN
7,Arab World,ARB,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,6.922033,6.972142,7.075062,7.066516,7.040109,6.995730,...,3.425198,3.324269,3.255093,3.208269,3.145588,3.107767,3.089751,NaN,NaN,NaN
36,Central Europe and the Baltics,CEB,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,2.491785,2.397857,2.307034,2.311055,2.258053,2.205929,...,1.589114,1.581897,1.578255,1.567430,1.568073,1.493944,1.407210,NaN,NaN,NaN
38,Channel Islands,CHI,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,2.340000,2.410000,2.520000,2.630000,2.660000,2.570000,...,1.410000,1.370000,1.350000,1.330000,1.360000,1.370000,1.370000,NaN,NaN,NaN
49,Caribbean small states,CSS,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,5.850236,5.786310,5.763466,5.693914,5.586649,5.458156,...,1.937264,1.920452,1.891793,1.870362,1.839672,1.838485,1.831680,NaN,NaN,NaN
61,East Asia & Pacific (excluding high income),EAP,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,4.831102,4.377555,6.018551,7.057745,6.442371,6.386630,...,1.925831,1.740435,1.704804,1.527897,1.440493,1.385526,1.361404,NaN,NaN,NaN
62,Early-demographic dividend,EAR,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,6.153667,6.166689,6.176148,6.179525,6.176641,6.148528,...,2.515369,2.482159,2.427796,2.373251,2.341675,2.318952,2.298167,NaN,NaN,NaN
63,East Asia & Pacific,EAS,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,4.552019,4.158861,5.526641,6.388446,5.863959,5.819039,...,1.870103,1.699158,1.662106,1.496726,1.416783,1.362728,1.335580,NaN,NaN,NaN
64,Europe & Central Asia (excluding high income),ECA,"Fertility rate, total (births per woman)",SP.DYN.TFRT.IN,3.941829,3.930688,3.916270,3.889028,3.829172,3.775436,...,2.077557,2.071648,2.058539,2.049482,2.054122,1.998424,1.984012,NaN,NaN,NaN

In [7]:
df_countries.drop(df_countries.columns[[ 2, 3, 68, 69, 70]], axis=1, inplace=True)
df_groups.drop(df_groups.columns[[ 2, 3, 68, 69, 70]], axis=1, inplace=True)

In [16]:
df_avg_n=df_countries['1960'].mean()
df_avg_l=df_countries['2023'].mean()
print(f"The mean global birth rate in 1960 was {df_avg_n:.3} while in 2023 it dropped to {df_avg_l:.3}")

The mean global birth rate in 1960 was 5.44 while in 2023 it dropped to 2.38

In [18]:
df_countries.to_csv("../../data/reduced_data/fertility_rates/fertility-countries.csv", index=False)

In [19]:
df_groups.to_csv("../../data/reduced_data/fertility_rates/fertility-groups.csv", index=False)