# WE WILL WORK ON REDUCING THE DATA TO ONLY THE SECTIONS WE NEED

In [2]:
import pandas as pd

### As we saw previously the data was split into regional and national info

In [3]:
import pycountry as pco

In [4]:
iso3_name_set = {country.alpha_3 for country in pco.countries}
iso3_name_set.add('XKX')

In [5]:
df = pd.read_csv('../../data/original_data/population-count/population.csv')

In [6]:
df_countries = df[df['Country Code'].isin(iso3_name_set)]
df_countries.head(10)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
0,Aruba,ABW,"Population, total",SP.POP.TOTL,54922.0,55578.0,56320.0,57002.0,57619.0,58190.0,...,108735.0,108908.0,109203.0,108587.0,107700.0,107310.0,107359.0,107995.0,NaN,NaN
2,Afghanistan,AFG,"Population, total",SP.POP.TOTL,9035043.0,9214083.0,9404406.0,9604487.0,9814318.0,10036008.0,...,35688935.0,36743039.0,37856121.0,39068979.0,40000412.0,40578842.0,41454761.0,42647492.0,NaN,NaN
4,Angola,AGO,"Population, total",SP.POP.TOTL,5231654.0,5301583.0,5354310.0,5408320.0,5464187.0,5521981.0,...,30234839.0,31297155.0,32375632.0,33451132.0,34532429.0,35635029.0,36749906.0,37885849.0,NaN,NaN
5,Albania,ALB,"Population, total",SP.POP.TOTL,1608800.0,1659800.0,1711319.0,1762621.0,1814135.0,1864791.0,...,2648285.0,2607733.0,2567801.0,2528480.0,2489762.0,2451636.0,2414095.0,2377128.0,NaN,NaN
6,Andorra,AND,"Population, total",SP.POP.TOTL,9510.0,10283.0,11086.0,11915.0,12764.0,13634.0,...,73763.0,75162.0,76474.0,77380.0,78364.0,79705.0,80856.0,81938.0,NaN,NaN
8,United Arab Emirates,ARE,"Population, total",SP.POP.TOTL,131334.0,137989.0,144946.0,152211.0,159692.0,167103.0,...,9223225.0,9346701.0,9445785.0,9401038.0,9575152.0,10074977.0,10483751.0,10986400.0,NaN,NaN
9,Argentina,ARG,"Population, total",SP.POP.TOTL,20386045.0,20726276.0,21072538.0,21421705.0,21769453.0,22112629.0,...,44288894.0,44654882.0,44973465.0,45191965.0,45312281.0,45407904.0,45538401.0,45696159.0,NaN,NaN
10,Armenia,ARM,"Population, total",SP.POP.TOTL,1863705.0,1927484.0,1991689.0,2056023.0,2120135.0,2183635.0,...,2979400.0,2969000.0,2962500.0,2961500.0,2962300.0,2969200.0,2964300.0,3033500.0,NaN,NaN
11,American Samoa,ASM,"Population, total",SP.POP.TOTL,20133.0,20666.0,21298.0,21966.0,22673.0,23406.0,...,51586.0,50908.0,50209.0,49761.0,49225.0,48342.0,47521.0,46765.0,NaN,NaN
12,Antigua and Barbuda,ATG,"Population, total",SP.POP.TOTL,55603.0,56540.0,57336.0,58138.0,59020.0,59970.0,...,90468.0,90926.0,91364.0,91846.0,92349.0,92840.0,93316.0,93772.0,NaN,NaN

In [7]:
df[df['Country Name']=='Not classified']

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
110,Not classified,INX,"Population, total",SP.POP.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Deleting unecessary columns / empty rows

In [8]:
df_countries.drop(df_countries[df_countries['Country Name']=='Not classified'].index, inplace=True)

In [9]:
df_countries.drop(df_countries.columns[[2, 3, 69, 70]], axis=1, inplace=True) ## 69,70 ALL Nans 2, 3 duplicated unecessary data

In [19]:
df_countries.reset_index(drop=True)
df_countries.head(10)

,Country Name,Country Code,1960,1961,1962,1963,1964,1965,1966,1967,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Aruba,ABW,54922.0,55578.0,56320.0,57002.0,57619.0,58190.0,58694.0,58990.0,...,107906.0,108727.0,108735.0,108908.0,109203.0,108587.0,107700.0,107310.0,107359.0,107995.0
2,Afghanistan,AFG,9035043.0,9214083.0,9404406.0,9604487.0,9814318.0,10036008.0,10266395.0,10505959.0,...,33831764.0,34700612.0,35688935.0,36743039.0,37856121.0,39068979.0,40000412.0,40578842.0,41454761.0,42647492.0
4,Angola,AGO,5231654.0,5301583.0,5354310.0,5408320.0,5464187.0,5521981.0,5581386.0,5641807.0,...,28157798.0,29183070.0,30234839.0,31297155.0,32375632.0,33451132.0,34532429.0,35635029.0,36749906.0,37885849.0
5,Albania,ALB,1608800.0,1659800.0,1711319.0,1762621.0,1814135.0,1864791.0,1914573.0,1965598.0,...,2731293.0,2689469.0,2648285.0,2607733.0,2567801.0,2528480.0,2489762.0,2451636.0,2414095.0,2377128.0
6,Andorra,AND,9510.0,10283.0,11086.0,11915.0,12764.0,13634.0,14626.0,15837.0,...,72174.0,72181.0,73763.0,75162.0,76474.0,77380.0,78364.0,79705.0,80856.0,81938.0
8,United Arab Emirates,ARE,131334.0,137989.0,144946.0,152211.0,159692.0,167103.0,173976.0,179700.0,...,8505237.0,8935095.0,9223225.0,9346701.0,9445785.0,9401038.0,9575152.0,10074977.0,10483751.0,10986400.0
9,Argentina,ARG,20386045.0,20726276.0,21072538.0,21421705.0,21769453.0,22112629.0,22453893.0,22799059.0,...,43477012.0,43900313.0,44288894.0,44654882.0,44973465.0,45191965.0,45312281.0,45407904.0,45538401.0,45696159.0
10,Armenia,ARM,1863705.0,1927484.0,1991689.0,2056023.0,2120135.0,2183635.0,2246159.0,2307492.0,...,3004600.0,2992300.0,2979400.0,2969000.0,2962500.0,2961500.0,2962300.0,2969200.0,2964300.0,3033500.0
11,American Samoa,ASM,20133.0,20666.0,21298.0,21966.0,22673.0,23406.0,24136.0,24863.0,...,52878.0,52245.0,51586.0,50908.0,50209.0,49761.0,49225.0,48342.0,47521.0,46765.0
12,Antigua and Barbuda,ATG,55603.0,56540.0,57336.0,58138.0,59020.0,59970.0,60900.0,61837.0,...,89409.0,89969.0,90468.0,90926.0,91364.0,91846.0,92349.0,92840.0,93316.0,93772.0

In [18]:
df_groups=df[~df['Country Code'].isin(iso3_name_set)]
df_groups.head(10)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
1,Africa Eastern and Southern,AFE,"Population, total",SP.POP.TOTL,1.300757e+08,1.335349e+08,1.371717e+08,1.409455e+08,1.449041e+08,1.490335e+08,...,6.400587e+08,6.578011e+08,6.759502e+08,6.944461e+08,7.130909e+08,7.318214e+08,7.504914e+08,7.692809e+08,NaN,NaN
3,Africa Western and Central,AFW,"Population, total",SP.POP.TOTL,9.763092e+07,9.970667e+07,1.018548e+08,1.040892e+08,1.063884e+08,1.087726e+08,...,4.408829e+08,4.521959e+08,4.633654e+08,4.745694e+08,4.859210e+08,4.973872e+08,5.093986e+08,5.217641e+08,NaN,NaN
7,Arab World,ARB,"Population, total",SP.POP.TOTL,9.154085e+07,9.393168e+07,9.642860e+07,9.903851e+07,1.017298e+08,1.044940e+08,...,4.283159e+08,4.359981e+08,4.442813e+08,4.537232e+08,4.606466e+08,4.713521e+08,4.821060e+08,4.926126e+08,NaN,NaN
36,Central Europe and the Baltics,CEB,"Population, total",SP.POP.TOTL,9.140131e+07,9.223138e+07,9.300859e+07,9.384002e+07,9.471580e+07,9.544099e+07,...,1.023375e+08,1.020742e+08,1.018643e+08,1.012158e+08,1.002057e+08,1.000719e+08,1.001837e+08,1.000620e+08,NaN,NaN
38,Channel Islands,CHI,"Population, total",SP.POP.TOTL,1.108080e+05,1.117820e+05,1.129530e+05,1.142340e+05,1.155610e+05,1.168790e+05,...,1.643190e+05,1.649490e+05,1.656390e+05,1.662350e+05,1.667410e+05,1.672150e+05,1.676910e+05,1.681260e+05,NaN,NaN
49,Caribbean small states,CSS,"Population, total",SP.POP.TOTL,2.558348e+06,2.614258e+06,2.670187e+06,2.728278e+06,2.784804e+06,2.839698e+06,...,4.366140e+06,4.407658e+06,4.443134e+06,4.459302e+06,4.479167e+06,4.497310e+06,4.519904e+06,4.539060e+06,NaN,NaN
61,East Asia & Pacific (excluding high income),EAP,"Population, total",SP.POP.TOTL,8.959615e+08,8.955346e+08,9.074730e+08,9.308108e+08,9.537835e+08,9.773669e+08,...,2.087239e+09,2.100699e+09,2.112290e+09,2.121866e+09,2.128554e+09,2.133560e+09,2.137528e+09,2.141122e+09,NaN,NaN
62,Early-demographic dividend,EAR,"Population, total",SP.POP.TOTL,9.689094e+08,9.941768e+08,1.020131e+09,1.046697e+09,1.074021e+09,1.101264e+09,...,3.274060e+09,3.314245e+09,3.355015e+09,3.396051e+09,3.432026e+09,3.470645e+09,3.511608e+09,3.552279e+09,NaN,NaN
63,East Asia & Pacific,EAS,"Population, total",SP.POP.TOTL,1.042819e+09,1.044750e+09,1.059217e+09,1.085095e+09,1.110651e+09,1.136869e+09,...,2.333476e+09,2.347576e+09,2.359762e+09,2.369421e+09,2.375118e+09,2.379617e+09,2.384441e+09,2.388319e+09,NaN,NaN
64,Europe & Central Asia (excluding high income),ECA,"Population, total",SP.POP.TOTL,1.288105e+08,1.316179e+08,1.344004e+08,1.371878e+08,1.399740e+08,1.426686e+08,...,2.443086e+08,2.464005e+08,2.485767e+08,2.503512e+08,2.518677e+08,2.505143e+08,2.487214e+08,2.502815e+08,NaN,NaN

In [12]:
df_groups.drop(df_groups[df_groups['Country Name']=='Not classified'].index, inplace=True)

In [13]:
df_groups.drop(df_groups.columns[[2, 3, 69, 70]], axis=1, inplace=True) ## 69,70 ALL Nans 2, 3 duplicated unecessary data

In [14]:
df_countries[df_countries['Country Name']=='South Sudan'].T.iloc[40:70]

             215
1998   5620068.0
1999   5771628.0
2000   6032267.0
2001   6308391.0
2002   6596806.0
2003   6903127.0
2004   7233041.0
2005   7590143.0
2006   7976526.0
2007   8388788.0
2008   8817647.0
2009   9243556.0
2010   9745953.0
2011  10288109.0
2012  10756240.0
2013  11166275.0
2014  11235073.0
2015  11107561.0
2016  10830102.0
2017  10259154.0
2018  10122977.0
2019  10423384.0
2020  10698467.0
2021  10865780.0
2022  11021177.0
2023  11483374.0
2024  11943408.0

In [15]:
df_countries.sum()[2:70] ##vALUES CONSISTENT WITH GROUPS DATA

1960    3008586057.0
1961    3049398996.0
1962    3103513758.0
1963    3169727675.0
1964    3236421104.0
            ...
2020    7821783266.0
2021    7887489204.0
2022    7956634224.0
2023    8030667956.0
2024    8108253520.0
Length: 65, dtype: object

In [16]:
df_countries.to_csv("../../data/reduced_data/population/population-countries.csv", index=False)

In [17]:
df_groups.to_csv("../../data/reduced_data/population/population-by-group.csv", index=False)