# WE WILL WORK ON REDUCING THE DATA TO ONLY THE SECTIONS WE NEED

In [33]:
import pandas as pd

### As we saw previously the data was split into regional and national info

In [34]:
import pycountry as pco

In [35]:
iso3_name_set = {country.alpha_3 for country in pco.countries}
iso3_name_set.add('XKX')

In [36]:
df = pd.read_csv('../../data/original_data/population-count/population.csv')

In [37]:
df_countries = df[df['Country Code'].isin(iso3_name_set)]
df_countries

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
0,Aruba,ABW,"Population, total",SP.POP.TOTL,54922.0,55578.0,56320.0,57002.0,57619.0,58190.0,...,108735.0,108908.0,109203.0,108587.0,107700.0,107310.0,107359.0,107995.0,NaN,NaN
2,Afghanistan,AFG,"Population, total",SP.POP.TOTL,9035043.0,9214083.0,9404406.0,9604487.0,9814318.0,10036008.0,...,35688935.0,36743039.0,37856121.0,39068979.0,40000412.0,40578842.0,41454761.0,42647492.0,NaN,NaN
4,Angola,AGO,"Population, total",SP.POP.TOTL,5231654.0,5301583.0,5354310.0,5408320.0,5464187.0,5521981.0,...,30234839.0,31297155.0,32375632.0,33451132.0,34532429.0,35635029.0,36749906.0,37885849.0,NaN,NaN
5,Albania,ALB,"Population, total",SP.POP.TOTL,1608800.0,1659800.0,1711319.0,1762621.0,1814135.0,1864791.0,...,2648285.0,2607733.0,2567801.0,2528480.0,2489762.0,2451636.0,2414095.0,2377128.0,NaN,NaN
6,Andorra,AND,"Population, total",SP.POP.TOTL,9510.0,10283.0,11086.0,11915.0,12764.0,13634.0,...,73763.0,75162.0,76474.0,77380.0,78364.0,79705.0,80856.0,81938.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260,Kosovo,XKX,"Population, total",SP.POP.TOTL,984846.0,1011421.0,1036950.0,1062737.0,1090270.0,1120168.0,...,1791019.0,1797086.0,1788891.0,1790151.0,1786079.0,1768096.0,1682668.0,1594353.0,NaN,NaN
261,"Yemen, Rep.",YEM,"Population, total",SP.POP.TOTL,5532301.0,5655232.0,5782221.0,5911135.0,6048006.0,6195593.0,...,33090921.0,34085182.0,35111408.0,36134863.0,37140230.0,38222876.0,39390799.0,40583164.0,NaN,NaN
262,South Africa,ZAF,"Population, total",SP.POP.TOTL,16440172.0,16908035.0,17418522.0,17954564.0,18511361.0,19089380.0,...,57635162.0,58613001.0,59587885.0,60562381.0,61502603.0,62378410.0,63212384.0,64007187.0,NaN,NaN
263,Zambia,ZMB,"Population, total",SP.POP.TOTL,3153729.0,3254086.0,3358099.0,3465907.0,3577017.0,3692086.0,...,17441320.0,17973569.0,18513839.0,19059395.0,19603607.0,20152938.0,20723965.0,21314956.0,NaN,NaN
264,Zimbabwe,ZWE,"Population, total",SP.POP.TOTL,3809389.0,3930401.0,4055959.0,4185877.0,4320006.0,4458462.0,...,14812482.0,15034452.0,15271368.0,15526888.0,15797210.0,16069056.0,16340822.0,16634373.0,NaN,NaN

In [38]:
df[df['Country Name']=='Not classified']

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
110,Not classified,INX,"Population, total",SP.POP.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Deleting unecessary columns / empty rows

In [39]:
df_countries.drop(df_countries[df_countries['Country Name']=='Not classified'].index, inplace=True)

In [40]:
df_countries.drop(df_countries.columns[[2, 3, 69, 70]], axis=1, inplace=True) ## 69,70 ALL Nans 2, 3 duplicated unecessary data

In [41]:
df_countries.reset_index(drop=True)

,Country Name,Country Code,1960,1961,1962,1963,1964,1965,1966,1967,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Aruba,ABW,54922.0,55578.0,56320.0,57002.0,57619.0,58190.0,58694.0,58990.0,...,107906.0,108727.0,108735.0,108908.0,109203.0,108587.0,107700.0,107310.0,107359.0,107995.0
1,Afghanistan,AFG,9035043.0,9214083.0,9404406.0,9604487.0,9814318.0,10036008.0,10266395.0,10505959.0,...,33831764.0,34700612.0,35688935.0,36743039.0,37856121.0,39068979.0,40000412.0,40578842.0,41454761.0,42647492.0
2,Angola,AGO,5231654.0,5301583.0,5354310.0,5408320.0,5464187.0,5521981.0,5581386.0,5641807.0,...,28157798.0,29183070.0,30234839.0,31297155.0,32375632.0,33451132.0,34532429.0,35635029.0,36749906.0,37885849.0
3,Albania,ALB,1608800.0,1659800.0,1711319.0,1762621.0,1814135.0,1864791.0,1914573.0,1965598.0,...,2731293.0,2689469.0,2648285.0,2607733.0,2567801.0,2528480.0,2489762.0,2451636.0,2414095.0,2377128.0
4,Andorra,AND,9510.0,10283.0,11086.0,11915.0,12764.0,13634.0,14626.0,15837.0,...,72174.0,72181.0,73763.0,75162.0,76474.0,77380.0,78364.0,79705.0,80856.0,81938.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,Kosovo,XKX,984846.0,1011421.0,1036950.0,1062737.0,1090270.0,1120168.0,1152586.0,1187667.0,...,1788274.0,1777568.0,1791019.0,1797086.0,1788891.0,1790151.0,1786079.0,1768096.0,1682668.0,1594353.0
211,"Yemen, Rep.",YEM,5532301.0,5655232.0,5782221.0,5911135.0,6048006.0,6195593.0,6351494.0,6516444.0,...,31159379.0,32109010.0,33090921.0,34085182.0,35111408.0,36134863.0,37140230.0,38222876.0,39390799.0,40583164.0
212,South Africa,ZAF,16440172.0,16908035.0,17418522.0,17954564.0,18511361.0,19089380.0,19690087.0,20314066.0,...,56723537.0,57259551.0,57635162.0,58613001.0,59587885.0,60562381.0,61502603.0,62378410.0,63212384.0,64007187.0
213,Zambia,ZMB,3153729.0,3254086.0,3358099.0,3465907.0,3577017.0,3692086.0,3812003.0,3936343.0,...,16399089.0,16914423.0,17441320.0,17973569.0,18513839.0,19059395.0,19603607.0,20152938.0,20723965.0,21314956.0
214,Zimbabwe,ZWE,3809389.0,3930401.0,4055959.0,4185877.0,4320006.0,4458462.0,4601217.0,4748307.0,...,14399013.0,14600294.0,14812482.0,15034452.0,15271368.0,15526888.0,15797210.0,16069056.0,16340822.0,16634373.0

In [42]:
df_groups=df[~df['Country Code'].isin(iso3_name_set)]
df_groups

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
1,Africa Eastern and Southern,AFE,"Population, total",SP.POP.TOTL,1.300757e+08,1.335349e+08,1.371717e+08,1.409455e+08,1.449041e+08,1.490335e+08,...,6.400587e+08,6.578011e+08,6.759502e+08,6.944461e+08,7.130909e+08,7.318214e+08,7.504914e+08,7.692809e+08,NaN,NaN
3,Africa Western and Central,AFW,"Population, total",SP.POP.TOTL,9.763092e+07,9.970667e+07,1.018548e+08,1.040892e+08,1.063884e+08,1.087726e+08,...,4.408829e+08,4.521959e+08,4.633654e+08,4.745694e+08,4.859210e+08,4.973872e+08,5.093986e+08,5.217641e+08,NaN,NaN
7,Arab World,ARB,"Population, total",SP.POP.TOTL,9.154085e+07,9.393168e+07,9.642860e+07,9.903851e+07,1.017298e+08,1.044940e+08,...,4.283159e+08,4.359981e+08,4.442813e+08,4.537232e+08,4.606466e+08,4.713521e+08,4.821060e+08,4.926126e+08,NaN,NaN
36,Central Europe and the Baltics,CEB,"Population, total",SP.POP.TOTL,9.140131e+07,9.223138e+07,9.300859e+07,9.384002e+07,9.471580e+07,9.544099e+07,...,1.023375e+08,1.020742e+08,1.018643e+08,1.012158e+08,1.002057e+08,1.000719e+08,1.001837e+08,1.000620e+08,NaN,NaN
38,Channel Islands,CHI,"Population, total",SP.POP.TOTL,1.108080e+05,1.117820e+05,1.129530e+05,1.142340e+05,1.155610e+05,1.168790e+05,...,1.643190e+05,1.649490e+05,1.656390e+05,1.662350e+05,1.667410e+05,1.672150e+05,1.676910e+05,1.681260e+05,NaN,NaN
49,Caribbean small states,CSS,"Population, total",SP.POP.TOTL,2.558348e+06,2.614258e+06,2.670187e+06,2.728278e+06,2.784804e+06,2.839698e+06,...,4.366140e+06,4.407658e+06,4.443134e+06,4.459302e+06,4.479167e+06,4.497310e+06,4.519904e+06,4.539060e+06,NaN,NaN
61,East Asia & Pacific (excluding high income),EAP,"Population, total",SP.POP.TOTL,8.959615e+08,8.955346e+08,9.074730e+08,9.308108e+08,9.537835e+08,9.773669e+08,...,2.087239e+09,2.100699e+09,2.112290e+09,2.121866e+09,2.128554e+09,2.133560e+09,2.137528e+09,2.141122e+09,NaN,NaN
62,Early-demographic dividend,EAR,"Population, total",SP.POP.TOTL,9.689094e+08,9.941768e+08,1.020131e+09,1.046697e+09,1.074021e+09,1.101264e+09,...,3.274060e+09,3.314245e+09,3.355015e+09,3.396051e+09,3.432026e+09,3.470645e+09,3.511608e+09,3.552279e+09,NaN,NaN
63,East Asia & Pacific,EAS,"Population, total",SP.POP.TOTL,1.042819e+09,1.044750e+09,1.059217e+09,1.085095e+09,1.110651e+09,1.136869e+09,...,2.333476e+09,2.347576e+09,2.359762e+09,2.369421e+09,2.375118e+09,2.379617e+09,2.384441e+09,2.388319e+09,NaN,NaN
64,Europe & Central Asia (excluding high income),ECA,"Population, total",SP.POP.TOTL,1.288105e+08,1.316179e+08,1.344004e+08,1.371878e+08,1.399740e+08,1.426686e+08,...,2.443086e+08,2.464005e+08,2.485767e+08,2.503512e+08,2.518677e+08,2.505143e+08,2.487214e+08,2.502815e+08,NaN,NaN
65,Europe & Central Asia,ECS,"Population, total",SP.POP.TOTL,6.678874e+08,6.755486e+08,6.833412e+08,6.911894e+08,6.990584e+08,7.066834e+08,...,9.150658e+08,9.186893e+08,9.219322e+08,9.236645e+08,9.243811e+08,9.242345e+08,9.247735e+08,9.282632e+08,NaN,NaN
68,Euro area,EMU,"Population, total",SP.POP.TOTL,2.701490e+08,2.724730e+08,2.748152e+08,2.772053e+08,2.796211e+08,2.820283e+08,...,3.448102e+08,3.458646e+08,3.464966e+08,3.469861e+08,3.472072e+08,3.482002e+08,3.497627e+08,3.511619e+08,NaN,NaN
73,European Union,EUU,"Population, total",SP.POP.TOTL,3.577105e+08,3.606816e+08,3.637080e+08,3.668408e+08,3.700550e+08,3.731292e+08,...,4.453211e+08,4.463299e+08,4.469105e+08,4.468710e+08,4.462274e+08,4.472027e+08,4.488975e+08,4.502282e+08,NaN,NaN
74,Fragile and conflict affected situations,FCS,"Population, total",SP.POP.TOTL,2.444616e+08,2.497374e+08,2.552281e+08,2.608950e+08,2.667195e+08,2.726764e+08,...,9.312229e+08,9.518516e+08,9.730352e+08,9.949011e+08,1.016907e+09,1.036390e+09,1.057033e+09,1.081768e+09,NaN,NaN
95,High income,HIC,"Population, total",SP.POP.TOTL,9.082573e+08,9.194493e+08,9.308329e+08,9.421416e+08,9.534779e+08,9.644597e+08,...,1.380320e+09,1.385103e+09,1.389770e+09,1.393473e+09,1.391815e+09,1.398002e+09,1.408190e+09,1.417842e+09,NaN,NaN
98,Heavily indebted poor countries (HIPC),HPC,"Population, total",SP.POP.TOTL,1.636505e+08,1.676349e+08,1.717717e+08,1.760633e+08,1.805377e+08,1.852086e+08,...,7.793900e+08,8.020207e+08,8.246491e+08,8.477433e+08,8.709300e+08,8.939063e+08,9.173043e+08,9.414130e+08,NaN,NaN
102,IBRD only,IBD,"Population, total",SP.POP.TOTL,1.893705e+09,1.915613e+09,1.950275e+09,1.996753e+09,2.043310e+09,2.090210e+09,...,4.765773e+09,4.806982e+09,4.845075e+09,4.878297e+09,4.905213e+09,4.928196e+09,4.952212e+09,4.979422e+09,NaN,NaN
103,IDA & IBRD total,IBT,"Population, total",SP.POP.TOTL,2.289192e+09,2.321079e+09,2.366118e+09,2.423349e+09,2.481068e+09,2.539564e+09,...,6.440012e+09,6.518058e+09,6.594216e+09,6.666470e+09,6.732651e+09,6.794724e+09,6.858522e+09,6.926222e+09,NaN,NaN
104,IDA total,IDA,"Population, total",SP.POP.TOTL,3.954874e+08,4.054661e+08,4.158429e+08,4.265956e+08,4.377586e+08,4.493548e+08,...,1.674238e+09,1.711077e+09,1.749141e+09,1.788174e+09,1.827439e+09,1.866528e+09,1.906309e+09,1.946801e+09,NaN,NaN
105,IDA blend,IDB,"Population, total",SP.POP.TOTL,1.244755e+08,1.276888e+08,1.310493e+08,1.345635e+08,1.382084e+08,1.419922e+08,...,5.900241e+08,6.019519e+08,6.140173e+08,6.264403e+08,6.391963e+08,6.518959e+08,6.643959e+08,6.769577e+08,NaN,NaN
107,IDA only,IDX,"Population, total",SP.POP.TOTL,2.710119e+08,2.777773e+08,2.847935e+08,2.920322e+08,2.995502e+08,3.073626e+08,...,1.084214e+09,1.109125e+09,1.135124e+09,1.161733e+09,1.188242e+09,1.214632e+09,1.241913e+09,1.269843e+09,NaN,NaN
110,Not classified,INX,"Population, total",SP.POP.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
127,Latin America & Caribbean (excluding high income),LAC,"Population, total",SP.POP.TOTL,1.928559e+08,1.982985e+08,2.039148e+08,2.096753e+08,2.155582e+08,2.215355e+08,...,5.619572e+08,5.677112e+08,5.733117e+08,5.780915e+08,5.818842e+08,5.856488e+08,5.898895e+08,5.941586e+08,NaN,NaN
133,Latin America & Caribbean,LCN,"Population, total",SP.POP.TOTL,2.186247e+08,2.247373e+08,2.310383e+08,2.374997e+08,2.440806e+08,2.507509e+08,...,6.304150e+08,6.357781e+08,6.409624e+08,6.454982e+08,6.492361e+08,6.531081e+08,6.576165e+08,6.621864e+08,NaN,NaN
134,Least developed countries: UN classification,LDC,"Population, total",SP.POP.TOTL,2.450486e+08,2.509849e+08,2.571734e+08,2.635578e+08,2.701947e+08,2.771020e+08,...,1.008993e+09,1.033110e+09,1.058014e+09,1.083636e+09,1.109175e+09,1.134586e+09,1.160825e+09,1.187778e+09,NaN,NaN
135,Low income,LIC,"Population, total",SP.POP.TOTL,1.147490e+08,1.174492e+08,1.202475e+08,1.231538e+08,1.262035e+08,1.293882e+08,...,5.148905e+08,5.295220e+08,5.449810e+08,5.606431e+08,5.760766e+08,5.914815e+08,6.077747e+08,6.246081e+08,NaN,NaN
138,Lower middle income,LMC,"Population, total",SP.POP.TOTL,8.193161e+08,8.399216e+08,8.610156e+08,8.826504e+08,9.048114e+08,9.271022e+08,...,2.847931e+09,2.888562e+09,2.928617e+09,2.968399e+09,3.006243e+09,3.043358e+09,3.082003e+09,3.120981e+09,NaN,NaN
139,Low & middle income,LMY,"Population, total",SP.POP.TOTL,2.083719e+09,2.112957e+09,2.155317e+09,2.209806e+09,2.264731e+09,2.320529e+09,...,6.093972e+09,6.169659e+09,6.243563e+09,6.313914e+09,6.378324e+09,6.437946e+09,6.498875e+09,6.563502e+09,NaN,NaN
141,Late-demographic dividend,LTE,"Population, total",SP.POP.TOTL,1.094884e+09,1.096959e+09,1.111293e+09,1.137057e+09,1.162405e+09,1.188452e+09,...,2.285870e+09,2.298394e+09,2.308878e+09,2.316152e+09,2.320128e+09,2.323800e+09,2.326297e+09,2.328628e+09,NaN,NaN
152,"Middle East, North Africa, Afghanistan & Pakistan",MEA,"Population, total",SP.POP.TOTL,1.579334e+08,1.620687e+08,1.663909e+08,1.708813e+08,1.755487e+08,1.803611e+08,...,7.188877e+08,7.303623e+08,7.427145e+08,7.564053e+08,7.675785e+08,7.823494e+08,7.978015e+08,8.131461e+08,NaN,NaN
155,Middle income,MIC,"Population, total",SP.POP.TOTL,1.968969e+09,1.995508e+09,2.035070e+09,2.086652e+09,2.138528e+09,2.191141e+09,...,5.579081e+09,5.640137e+09,5.698582e+09,5.753271e+09,5.802247e+09,5.846465e+09,5.891100e+09,5.938894e+09,NaN,NaN
160,"Middle East, North Africa, Afghanistan & Pakis...",MNA,"Population, total",SP.POP.TOTL,1.518831e+08,1.557962e+08,1.598493e+08,1.640828e+08,1.684744e+08,1.730121e+08,...,6.567676e+08,6.684474e+08,6.804910e+08,6.925320e+08,7.044588e+08,7.165087e+08,7.290774e+08,7.416909e+08,NaN,NaN
169,North America,NAC,"Population, total",SP.POP.TOTL,1.986226e+08,2.020051e+08,2.051962e+08,2.082513e+08,2.112604e+08,2.140285e+08,...,3.632173e+08,3.656660e+08,3.679088e+08,3.696707e+08,3.704043e+08,3.730180e+08,3.769544e+08,3.814642e+08,NaN,NaN
180,OECD members,OED,"Population, total",SP.POP.TOTL,8.095802e+08,8.207960e+08,8.322274e+08,8.436508e+08,8.551350e+08,8.663009e+08,...,1.348127e+09,1.356471e+09,1.364146e+09,1.369310e+09,1.371785e+09,1.378566e+09,1.387898e+09,1.396877e+09,NaN,NaN
182,Other small states,OSS,"Population, total",SP.POP.TOTL,5.297024e+06,5.374964e+06,5.476102e+06,5.578740e+06,5.680872e+06,5.779625e+06,...,1.198937e+07,1.213527e+07,1.228191e+07,1.241733e+07,1.254189e+07,1.269900e+07,1.282213e+07,1.293188e+07,NaN,NaN
190,Pre-demographic dividend,PRE,"Population, total",SP.POP.TOTL,1.889203e+08,1.933427e+08,1.980050e+08,2.028793e+08,2.079585e+08,2.132460e+08,...,9.205687e+08,9.463172e+08,9.723025e+08,9.986243e+08,1.024960e+09,1.051202e+09,1.078224e+09,1.105952e+09,NaN,NaN
196,Pacific island small states,PSS,"Population, total",SP.POP.TOTL,9.121200e+05,9.382440e+05,9.654300e+05,9.935240e+05,1.022081e+06,1.051140e+06,...,2.509999e+06,2.542009e+06,2.568656e+06,2.595522e+06,2.625493e+06,2.656049e+06,2.689224e+06,2.722467e+06,NaN,NaN
197,Post-demographic dividend,PST,"Population, total",SP.POP.TOTL,7.563591e+08,7.654421e+08,7.746788e+08,7.837365e+08,7.927351e+08,8.014513e+08,...,1.107162e+09,1.111377e+09,1.114899e+09,1.117007e+09,1.116583e+09,1.117395e+09,1.121316e+09,1.128378e+09,NaN,NaN
203,South Asia,SAS,"Population, total",SP.POP.TOTL,5.079193e+08,5.204169e+08,5.331625e+08,5.461112e+08,5.593614e+08,5.724983e+08,...,1.572520e+09,1.589165e+09,1.605413e+09,1.621073e+09,1.634785e+09,1.648010e+09,1.662581e+09,1.677385e+09,NaN,NaN
214,Sub-Saharan Africa (excluding high income),SSA,"Population, total",SP.POP.TOTL,2.062883e+08,2.112926e+08,2.165172e+08,2.219379e+08,2.275797e+08,2.334480e+08,...,9.711793e+08,9.972361e+08,1.023481e+09,1.049999e+09,1.076774e+09,1.103704e+09,1.131078e+09,1.158864e+09,NaN,NaN
216,Sub-Saharan Africa,SSF,"Population, total",SP.POP.TOTL,2.277067e+08,2.332416e+08,2.390264e+08,2.450347e+08,2.512925e+08,2.578061e+08,...,1.080942e+09,1.109997e+09,1.139316e+09,1.169015e+09,1.199012e+09,1.229209e+09,1.259890e+09,1.291045e+09,NaN,NaN
217,Small states,SST,"Population, total",SP.POP.TOTL,8.767492e+06,8.927466e+06,9.111719e+06,9.300542e+06,9.487757e+06,9.670463e+06,...,1.886551e+07,1.908493e+07,1.929370e+07,1.947216e+07,1.964655e+07,1.985236e+07,2.003126e+07,2.019340e+07,NaN,NaN
229,East Asia & Pacific (IDA & IBRD countries),TEA,"Population, total",SP.POP.TOTL,8.842525e+08,8.835582e+08,8.952249e+08,9.182590e+08,9.409095e+08,9.641639e+08,...,2.061450e+09,2.074797e+09,2.086282e+09,2.095759e+09,2.102351e+09,2.107261e+09,2.111139e+09,2.114653e+09,NaN,NaN
230,Europe & Central Asia (IDA & IBRD countries),TEC,"Population, total",SP.POP.TOTL,3.087594e+08,3.134836e+08,3.181861e+08,3.229615e+08,3.277748e+08,3.323752e+08,...,4.580103e+08,4.599469e+08,4.619332e+08,4.628423e+08,4.631044e+08,4.609423e+08,4.586022e+08,4.597340e+08,NaN,NaN
235,Latin America & the Caribbean (IDA & IBRD coun...,TLA,"Population, total",SP.POP.TOTL,2.086711e+08,2.145827e+08,2.206683e+08,2.268997e+08,2.332556e+08,2.397087e+08,...,6.147767e+08,6.202744e+08,6.254673e+08,6.300510e+08,6.338626e+08,6.378378e+08,6.423979e+08,6.470037e+08,NaN,NaN
237,"Middle East, North Africa, Afghanistan & Pakis...",TMN,"Population, total",SP.POP.TOTL,1.518831e+08,1.557962e+08,1.598493e+08,1.640828e+08,1.684744e+08,1.730121e+08,...,6.523128e+08,6.638783e+08,6.758057e+08,6.877288e+08,6.995361e+08,7.114650e+08,7.239117e+08,7.364018e+08,NaN,NaN
239,South Asia (IDA & IBRD),TSA,"Population, total",SP.POP.TOTL,5.079193e+08,5.204169e+08,5.331625e+08,5.461112e+08,5.593614e+08,5.724983e+08,...,1.572520e+09,1.589165e+09,1.605413e+09,1.621073e+09,1.634785e+09,1.648010e+09,1.662581e+09,1.677385e+09,NaN,NaN
240,Sub-Saharan Africa (IDA & IBRD countries),TSS,"Population, total",SP.POP.TOTL,2.277067e+08,2.332416e+08,2.390264e+08,2.450347e+08,2.512925e+08,2.578061e+08,...,1.080942e+09,1.109997e+09,1.139316e+09,1.169015e+09,1.199012e+09,1.229209e+09,1.259890e+09,1.291045e+09,NaN,NaN
248,Upper middle income,UMC,"Population, total",SP.POP.TOTL,1.149653e+09,1.155586e+09,1.174054e+09,1.204002e+09,1.233716e+09,1.264039e+09,...,2.731150e+09,2.751575e+09,2.769965e+09,2.784872e+09,2.796004e+09,2.803106e+09,2.809098e+09,2.817913e+09,NaN,NaN
258,World,WLD,"Population, total",SP.POP.TOTL,3.021513e+09,3.062768e+09,3.117372e+09,3.184063e+09,3.251253e+09,3.318998e+09,...,7.614523e+09,7.697234e+09,7.778009e+09,7.854748e+09,7.920515e+09,7.989545e+09,8.064058e+09,8.141809e+09,NaN,NaN

In [43]:
df_groups.drop(df_groups[df_groups['Country Name']=='Not classified'].index, inplace=True)

In [44]:
df_groups.drop(df_groups.columns[[2, 3, 69, 70]], axis=1, inplace=True) ## 69,70 ALL Nans 2, 3 duplicated unecessary data

In [45]:
df_countries[df_countries['Country Name']=='South Sudan'].T.iloc[40:70]

             215
1998   5620068.0
1999   5771628.0
2000   6032267.0
2001   6308391.0
2002   6596806.0
2003   6903127.0
2004   7233041.0
2005   7590143.0
2006   7976526.0
2007   8388788.0
2008   8817647.0
2009   9243556.0
2010   9745953.0
2011  10288109.0
2012  10756240.0
2013  11166275.0
2014  11235073.0
2015  11107561.0
2016  10830102.0
2017  10259154.0
2018  10122977.0
2019  10423384.0
2020  10698467.0
2021  10865780.0
2022  11021177.0
2023  11483374.0
2024  11943408.0

In [46]:
df_countries.sum()[2:70] ##vALUES CONSISTENT WITH GROUPS DATA

1960    3008586057.0
1961    3049398996.0
1962    3103513758.0
1963    3169727675.0
1964    3236421104.0
            ...
2020    7821783266.0
2021    7887489204.0
2022    7956634224.0
2023    8030667956.0
2024    8108253520.0
Length: 65, dtype: object

In [47]:
df_countries.to_csv("../../data/reduced_data/population/population-countries.csv", index=False)

In [48]:
df_groups.to_csv("../../data/reduced_data/population/population-by-group.csv", index=False)